### ISSUE TITLE
Intenship at Datature

### ISSUE THREAD

**Issue by ghost** [joulev/joulev#1]
Hi Vu Van Dung!

This is Mithi from Datature. Would you like to have your internship with us starting April 2024? You can message me on Whatsapp +6592734431 . 

Thanks Dung!

- Mithi

**Comment by joulev** [comment]
Thanks a lot for this! I followed up in an email to you.

**Comment by ghost** [comment]
Thanks for your quick response Dung. Hope we can collaborate in the future...  :)

**Comment by ghost** [comment]
BTW Are you in SG right now or Vietnam? If in SG maybe we can meet for coffee one of these days!

**Comment by joulev** [comment]
@mithi-datature Unfortunately I'm in Vietnam right now :( Would really love to have a coffee with you too, but I'm effectively taking this semester off.
